version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: phalconDB-nginx
    ports:
      - "80:80"
    volumes:
      - ../phalcon-docker/nginx.conf:/etc/nginx/conf.d/default.conf 
      - ../backend:/var/www 
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - "../backend:/var/www"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mydatabase
      - DB_USERNAME=root
      - DB_PASSWORD=admin
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - "../frontend/r-nier:/app"
  #     - "/app/node_modules"
  #   command: ["npm", "run", "dev"]

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
    depends_on:
      - db

volumes:
  db_data:
  redis_data: